# PRODUCTION DOCKERFILE FOR GOOGLE CLOUD RUN
FROM node:22.20-alpine3.21 AS builder

WORKDIR /app/

RUN corepack enable 

COPY package*.json pnpm-lock.yaml ./

RUN pnpm install --frozen-lockfile

COPY . .

### Variables de build - Next.js las necesita en tiempo de compilación
ARG NEXT_PUBLIC_API_URL
ENV NEXT_PUBLIC_API_URL=$NEXT_PUBLIC_API_URL

ARG NEXT_PUBLIC_FRONTEND_URL
ENV NEXT_PUBLIC_FRONTEND_URL=$NEXT_PUBLIC_FRONTEND_URL

ARG BACKEND_URL
ENV BACKEND_URL=$BACKEND_URL

ENV NODE_ENV=production

# Build the project
RUN pnpm run build
# Delete dev dependencies
RUN pnpm prune --prod

# RUNNER STAGE
FROM node:22.20-alpine3.21 AS runner
WORKDIR /app

RUN corepack enable

COPY --from=builder /app/next.config.* ./
COPY --from=builder /app/package.json ./
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/.next ./.next
COPY --from=builder /app/public ./public

# Google Cloud Run usa el puerto 8080 por defecto
ENV PORT=8080
EXPOSE 8080

CMD ["sh", "-c", "pnpm start -p $PORT"]
