export { default as Header } from './Header';
export { default as HeroSlider } from './HeroSlider';
export { default as AboutEvent } from './AboutEvent';
export { default as MissionVision } from './MissionVision';
export { default as NewsCard } from './NewsCard';
export { default as NewsSection } from './NewsSection';
export { default as AboutUs } from './AboutUs';
export { default as Sponsors } from './Sponsors';
export { default as Footer } from './Footer';
